### ISSUE TITLE
Evaluation Details

### ISSUE THREAD

**Issue by aopolin-lv** [kristery/Elastic-DT#1]
Hello, authors. *Elastic Decision Transformer* provides a good view to investigate the stitch problem. I am now trying to reproduce the experimental result. 
However, there is a problem about evaluation period, and it is not explicitly illustrated in the *Decision Transformer* paper.

How do you evaluate your final results? For example, do you test the final model after training for 100k steps, or do you use another method?

**Comment by kristery** [comment]
Thank you for your interest in our work! We train the model for 500 epochs and then directly evaluate its performance.
